### PR TITLE
Add krew as a new Tool

### PR DESCRIPTION
**Pull request by enflo**
From the comment in the following Issue https://github.com/alpine-docker/k8s/issues/38 I open this PR to add Krew.

`DOCKER_CMD` = Docker Run of the image

```
$(DOCKER_CMD) bash -c "source ~/.bashrc" && kubectl krew update
$(DOCKER_CMD) bash -c "source ~/.bashrc" && kubectl krew install modify-secret ns grep
```

I could not avoid the `bash -c "source ~/.bashrc"` command before the `kubecl krew`, if someone knows how to fix it, I will be glad of this feedback.

### CODE REVIEW

**Comment by ozbillwang** [comment]
LGTM, thanks.

**Comment by ozbillwang** [comment]
the build job is failed after merged the PR

image

I built it locally, looks fine to me, not sure why it is failed with Pipeline build.

**Comment by ozbillwang** [comment]
All fixed.

**Comment by ozbillwang** [comment]
@enflo 

Please confirm.  You need pull the image `docker pull alpine/k8s:<tag>`

**Comment by enflo** [comment]
UI, sorry, I didn't pass the build because I don't have a CI configured. I apologize for having to resolve several issues.

**Comment by ozbillwang** [comment]
no worried. 

Did you have change to run a test with the latest images the pipeline built? I need make sure if krew works or not.

image

**Comment by enflo** [comment]
@ozbillwang Krew just work

I used in my code project, executing "source ~/.bashrc" before execute krew

$(DOCKER_CMD) bash -c "source ~/.bashrc" && kubectl krew update
$(DOCKER_CMD) bash -c "source ~/.bashrc" && kubectl krew install modify-secret ns grep

**Comment by ozbillwang** [comment]
Thanks for the confirmation.

**Pull request merged**
