### PR TITLE
Add `envsubst` command

### PR DESCRIPTION
**Pull request by nooop3**

### CODE REVIEW

**Comment by ozbillwang** [comment]
what's it for? related to Kubernetes?

**Comment by nooop3** [comment]
> what's it for? related to Kubernetes?

There are some config files/scripts that contain credential info and we need to add these files in the VCS. So we want to use the `envsubst` command to replace the variables for some kubectl commands.

**Comment by ozbillwang** [comment]
could you handle it before you run the k8s commands? that means out of the k8s container?

**Comment by nooop3** [comment]
In my situation, I'm using this image in our GitLab CI/CD jobs. We need this command to pass environment variables to kubectl to make the changes, so I think it's better if we can use the `envsubst` command in the container. Thanks.

**Comment by ozbillwang** [comment]
so if you need handle it with environment varialbe, you shouldn't do it in k8s. 

you can manage environment variables easily out of the containers. 

for your reference: 

Docker run:

```
--env , -e |   | Set environment variables
```

for k8s, reference this official document: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by nooop3** [comment]
Okay, thanks for your advice. Maybe my situation is more complicated, I
need to parse multi environment variables from JSON/yaml files. I have
built another dock image to solve the problem. Thanks anyway.

**Comment by ozbillwang** [comment]
do you know Helm? that tool looks more suitable for you. It has some internal functions to handle json key/value easily.

**Comment by nooop3** [comment]
Sounds good. I will try Helm later. Thank you.

**Comment by kingchad1989** [comment]
I was actually just looking for this too when I came across this PR, thanks for merging

**Pull request closed without merging**
